import { z } from 'zod';

export const archetypeName = z.enum([
	'Architect',
	'Artist',
	'Bully',
	'Child',
	'Competitor',
	'Con Artist',
	'Conformist',
	'Curious',
	'Curmudgeon',
	'Cultured',
	'Enigma',
	'Fanatic',
	'Fighter',
	'Freak',
	'Free Spirit',
	'Judge',
	'Know-It-All',
	'Introvert',
	'Leader',
	'Loner',
	'Loose Cannon',
	'Martyr',
	'Mediator',
	'Mercenary',
	'Monster',
	'Penitent',
	'Protector',
	'Rationalist',
	'Royalty',
	'Survivor',
	'Type-A Personality',
	'Teacher',
	'Traditionalist',
	'Troublemaker',
	'Toady',
	'Trickster',
	'Unflappable',
	'Untrustworthy'
]);
export type ArchetypeName = z.infer<typeof archetypeName>;
