import { z } from 'zod';

export const itemQualityName = z.enum([
	'Accurate',
	'Antique',
	'Ammo Capacity I',
	'Ammo Capacity II',
	'Armor Piercing',
	'Artisan',
	'Automatic',
	'Balanced',
	'Ballistic',
	'Brutal',
	'Chest Plate',
	'Cold Iron',
	'Concealable',
	'Customized',
	'Deadly',
	'Disabling',
	'Fast',
	'Flashy',
	'Full Body',
	'Flaming',
	'Hardened',
	'HazMat',
	'Impact Absorption',
	'Incendiary Ammunition',
	'Knockback',
	'Long Range',
	'Masterwork',
	'Nondescript',
	'Trip',
	'Impaling',
	'Quick Draw',
	'Rapid Reload',
	'Reach',
	'Rugged',
	'Secure',
	'Silver',
	'Silver Ammunition',
	'Spread',
	'Staking',
	'Strange Composition',
	'Streamlined',
	'Stylish',
	'Sturdy',
	'Superior'
]);
export type ItemQualityName = z.infer<typeof itemQualityName>;
