import { z } from 'zod';

export const flawName = z.enum([
	'Accused of Heresy',
	'Addiction',
	'All My Friends are Dead',
	'Amnesia',
	'Anosmia',
	'Archaic',
	'Artless',
	'Awkward Mobility',
	'Bad Luck',
	'Bad Sight',
	'Bastard Childe',
	'Beacon of the Unholy',
	'Beast in the Mirror',
	'Bestial Instinct',
	'Black Sheep',
	'Blackened Aura',
	'Blood Rot',
	'Blunted Fangs',
	'Bound to the Earth',
	'Cannot Cross Running Water',
	'Careless',
	'Carrion Comfort',
	'Childlike',
	'Clay Pigeon',
	'Coldly Logical',
	'Confusing Realities',
	'Conspicuous Consumption',
	'Cowardly Beast',
	'Cowardly Blood',
	'Crisis of Faith',
	'Curiosity',
	'Cursed',
	'Dark Fate',
	'Dark Secret',
	'Dead Giveaway',
	'Death Sight',
	'Death’s Reflection',
	'Deep Sleeper',
	'Deer in Headlights',
	"Devil's Mark",
	'Diluted Blood',
	'Discipline Illiterate',
	'Disease Carrier',
	'Dual Caste',
	'Dubious Loyalties',
	'Dull',
	'Eerie Presence',
	'Escaped Shovelhead',
	'Essence of Connaught',
	'Falling Apart',
	'Feeding Fetish',
	'Flesh of the Corpse',
	'Forgiven Diablerie',
	'Foul Blood',
	'Fragile Bones',
	'Fusion',
	'Gehenna Prophet',
	'Grip of the Damned',
	'Hard of Hearing',
	'Haunted',
	'Humble Gardener',
	'Hunted',
	'Illiterate',
	'Impatient',
	'Inept',
	'Infamous Brood',
	'Infernal Thrall',
	'Insubordinate',
	'Intolerance',
	'Known to be Dead',
	'Lead Foot',
	'Lesser Generation',
	'Living Art',
	'Lost Svadharma',
	'Low Down and Dirty',
	'Low Pain Threshold',
	'Magic Susceptibility',
	'Methuselah’s Thirst',
	'Mistrusted',
	'Mångha’s Disdain',
	'Necrophile',
	'Nightmares',
	'No Encore',
	'Non-Serviam',
	'Notoriety',
	'Number One Fan',
	'Obsession',
	'Obvious Predator',
	'Offal Appetite',
	'Once Enslaved',
	'One Eye',
	'Overconfident',
	'Overstimulated',
	'Parasitic Infestation',
	'Pedantic',
	'Permanent Wound',
	'Pied Piper',
	'Poseidon’s Call',
	'Prey Exclusion',
	'Rat In A Cage',
	'Repelled by Religion',
	'Revenant Family Weakness',
	'Ritually Inept',
	'Roadkill',
	'Scar Tissue',
	'Sectarian',
	'Selective Memory',
	'Serpentine Physiology',
	'Shadow Walker',
	'Short Attention Span',
	'Short Fuse',
	'Shroud Inept',
	'Slow Healing',
	'Slow Reactions',
	'Snake Charmed',
	'Soul Shard',
	'Species Speech',
	'Specters of the Past',
	'Spell Components',
	'Stage Fright',
	'Stolen Potential',
	'Stone Scarecrow',
	'Stuffed Shirt',
	'Tainted Embrace',
	'Technophobe',
	'Temperament of Storms',
	'Tenuous Loyalty',
	'Thin Blooded',
	'Thirst for Innocence',
	'Tone Deaf',
	'Trouble Magnet',
	'Twice Bound to the Council',
	'Unblinking Eyes',
	'Unbroken',
	'Uncontrollable',
	'Untrained Combatant',
	'Vow of Peace',
	'Vulnerable to Silver',
	'Weak Stomach',
	'Weak-Willed'
]);
export type FlawName = z.infer<typeof flawName>;
