import { z } from 'zod';

export const meritName = z.enum([
	'Absent Sway',
	'Abstract Awareness',
	'Abyssal Horror',
	'Acute Sense',
	'Adaptive',
	'Addictive Blood',
	'Additional Common Discipline',
	'Additional Uncommon Discipline',
	'All The Best Toys',
	'Ambidextrous',
	'Angelic Visage',
	'Antiquities',
	'Aquatic Predator',
	'Arcane',
	'Arcane Branding',
	'Architect of the Tower',
	'Ardent Companion',
	'Art Imitates Life',
	'Artist’s Blessing',
	'Athenaeum of the Hive',
	'Aura of Command',
	'Auspicious',
	'Awakening the Steel',
	'Bane of the Aeons',
	'Bane’s Blessing',
	'Beauty of the Beholder',
	'Become the Slasher',
	'Beneath Notice',
	'Black Hand Membership',
	'Blasé',
	'Blessing of the Gorgons',
	'Blight of the Ever-Hungry',
	'Blood Deceit',
	'Blood in the Water',
	'Blood Knows the Way',
	'Blood of the Ancients',
	'Blood of the Tzimisce',
	'Blood Secrets',
	'Bloodline: Ahrimanes',
	'Bloodline: Ananke',
	'Bloodline: Anda',
	'Bloodline: Angellis Ater',
	'Bloodline: Brahman',
	'Bloodline: Bratovitch',
	'Bloodline: Carpathian',
	'Bloodline: Corsairs',
	'Bloodline: Coyote',
	'Bloodline: Creeps',
	'Bloodline: Crusaders',
	'Bloodline: Healer',
	'Bloodline: Ishtarri',
	'Bloodline: Kiasyd',
	'Bloodline: Knights of the Moon',
	'Bloodline: Koldun',
	'Bloodline: Lamia',
	'Bloodline: Noiad',
	'Bloodline: Premascine',
	'Bloodline: Samedi',
	'Bloodline: Sorcerer',
	'Bloodline: Telyav',
	'Bloodline: Tlacique',
	'Bloodline: True Brujah',
	'Bloodline: Vipers',
	'Bloodline: Vizier',
	'Bloodline: Volgirre',
	'Bonds of Stolen Vitae',
	'Born in Shadow',
	'Borrowed Time',
	'Breaking Point',
	'Brotherhood',
	'Burning Wrath',
	'Calm Heart',
	'Chimerical Templar',
	'Chosen of Cappadocius',
	'Chosen of the Crone',
	'Clear Sighted',
	'Code of Honor',
	'Consecrated Grove',
	'Countermagic',
	"Dancer's Grace",
	'Daredevil',
	'Dark Magics',
	'Dark Statue',
	'Dauntless',
	'Death Becomes You',
	'Death’s Virtuoso',
	'Demon Slayer',
	'Dhampir',
	'Diva',
	'Dust in the Wind',
	'Ear to the Ground',
	'Eclipsed Blood',
	'Efficient Digestion',
	'Efficient Learner',
	'Elder of the Revolution',
	'Emissary to the Camarilla',
	'Emptiness of Faith',
	'Ephemeral Rhapsody',
	'Escape Artist',
	'Executioner',
	'Expanded Consciousness',
	'Extrasensory Perceptions',
	'Fae Blood',
	'Fanatic',
	'Favored of Inauhaten',
	'Favored of the Decani',
	'Fear Factor',
	'Fervent Iconoclast',
	'Flexible Morals',
	'Flight',
	'Flower of Kupala',
	'Forge of the Soul',
	'Ghostly Retainer',
	'Golconda Seeker',
	'Greater Colors',
	'Hard as Steel',
	'Hidden Advantage',
	'Humble Abode',
	'Immortal Beauty',
	'Inceptor',
	'Infernal Acolyte',
	'Infernal Heritage',
	'Infernal Power',
	'Inquisition Membership',
	'Intense Vitality',
	'Iron Heart',
	'Iron Scales',
	'Iron Will',
	'Itty Bitty Living Space',
	'Jack be Nimble',
	'Jaded Existence',
	'Keeper of a Sacred Text',
	'Knowledge is a Sword',
	'Kupala’s Bounty',
	'Labyrinthine Mind',
	'Lichborne',
	'Lifegiver',
	'Light Sleeper',
	'Lion of the Cause',
	'Loa’s Rebirth',
	'Local Legend',
	'Loremaster',
	'Luck of the Damned',
	'Lucky',
	'Machiavellian Prodigy',
	'Madness Hunter',
	'Magic Resistance',
	'Malkavian Time',
	'Master of Puppets',
	'Master of the Hounds',
	'Master of Vice',
	'Medium',
	'Memento Mori',
	'Method to the Madness',
	'Mind Games',
	'Moloch’s Heir',
	'Moniker',
	'Monopoly',
	'Mook',
	'Moon Bound',
	'Moral Compass',
	'Natural Linguist',
	'Nature Walk',
	'Necromantic Expertise',
	'Necromantic Insight',
	'Necromantic Prowess',
	'Necromantic Training',
	'Necrosynthesis',
	'No Place Like Home',
	'Not My Time',
	'Not On My Watch',
	'Obsessive Study',
	'Obsidian Claws',
	'Old Dog',
	'Old Habits',
	'Oracular Ability',
	'Pack Player',
	'Painfully Shy',
	'Paragon',
	'Parley',
	'Path Adherent',
	'Path of Blood',
	'Path of Caine',
	'Path of Cathari',
	'Path of Chivalry',
	'Path of Death & the Soul',
	'Path of Ecstasy',
	'Path of Entelechy',
	'Path of Evil Revelations',
	'Path of Feral Heart',
	'Path of Harmony',
	'Path of Heaven',
	'Path of Honorable Accord',
	'Path of Lilith',
	'Path of Metamorphosis',
	'Path of Night',
	'Path of Nocturnal Redemption',
	'Path of Orion',
	'Path of Paradox',
	'Path of Power & the Inner Voice',
	'Path of Scorched Heart',
	'Path of the Hive',
	'Path of Typhon-Set',
	'Personal Cult',
	'Personal Masquerade',
	'Piece That Remains',
	'Pierce the Veil',
	'Pierced Shroud',
	'Pliable Blood',
	'Polymorphic Demeanor',
	'Power Broker',
	'Power Object',
	'Prestigious Sire',
	'Preternatural Awareness',
	'Primacy of the Blood',
	'Prodigy of the Flesh',
	'Protean Blood',
	'Quick Caster',
	'Quixotic',
	'Rare Clan',
	'Regal Bearing',
	'Renaissance Mindset',
	'Rending',
	'Reputation',
	'Restricted Clan',
	'Revelator',
	'Rhythm of Battle',
	'Righteous Fury',
	'Ritual Fluency',
	'Ritual Master Necromancy',
	'Ritual Master Thaumaturgy',
	'Ritual Supremacy',
	'Rugged',
	'Runic Woads',
	'Rush of Battle',
	'Sage of the Spirits',
	'Sanctified',
	'Sanguine Anointing',
	'Sanguine Indulgence',
	'Scholar of the Sword',
	'Scholomonariue',
	'Scion of Death',
	'Scourge of Alecto',
	'Sea Witch',
	'Seasoned Traveler',
	'Seekers of the Hidden',
	'Serpentine Embrace',
	'Setite Sorcery',
	'Shadows of the Past',
	'Shady Dealings',
	'Shape of Beast’s Wrath',
	'Shedding the Snake’s Skin',
	'Shrinking Violet',
	'Sight Beyond Sight',
	'Skill Aptitude',
	'Skullduggery',
	'Slippery Customer',
	'Soaring Octaves',
	'Social Elite',
	'Social Nobility',
	'Song of the Fifth Trumpet',
	'Songs Beyond Mortal Ken',
	'Sophistry',
	'Sorcerous Dabbler',
	'Soul Economy',
	'Soul of the Wyld',
	'Spellslinger',
	'Spirit Guide',
	'Spiritual Animist',
	'Spiritual Armor',
	'Strength of Honor',
	'Strength of Madness',
	'Subtle as Hell',
	'Supernatural Aria',
	'Surprise Attack',
	'Szlachta',
	'Talisman',
	'Talismongerer',
	'Tech Junkie',
	'Thaumaturgic Expertise',
	'Thaumaturgic Training',
	'Thaumaturgically Gifted',
	'The Beast Within',
	'The Blade Whisperer',
	'The Duty of Kings',
	'The Friendly Folk',
	'The Heart of the Matter',
	'The Judge’s Resilience',
	'The Man in Black',
	"The Master's Path",
	'Timely Intervention',
	'To Catch a Killer',
	'To the Manor Born',
	'Touched by an Angel',
	'Trials of the Blood',
	'Trusted Confessor',
	'Typhonic Beast',
	'Unbondable',
	'Uncommon Clan',
	'Unnatural Adaptation',
	'Unseeing Eye',
	'Unyielding',
	'Ventrue Royalty',
	'Versatile',
	'Vestiges of Greatness',
	'Visceral Artisan',
	'Volatile',
	'Voudoun Master',
	'Vozhd',
	'Waking Dream',
	'Walk the Abyss (Abyss Mysticism)',
	'Walking Dead',
	'Web of Knives',
	'Whisper of Life',
	'Whispers from Beyond',
	'Wild One',
	'Zealot'
]);
export type MeritName = z.infer<typeof meritName>;
