import { z } from 'zod';

export const techniqueName = z.enum([
	'Abrupt Internment',
	'Alchemical Attunement',
	'Alpha of the Pack',
	'An Da Shealladh',
	'Animal Succulence',
	'Animal Swarm',
	'Armor of Darkness',
	'Badger’s Hide',
	'Banshee’s Wail',
	'Beast’s Vigor',
	'Bestial Allure',
	'Black Mist',
	'Blind the Sun',
	'Bliss',
	'Blood Tempering',
	'Bonecraft Prodigy',
	'Bullet Time',
	'Bull’s Eye',
	'Call Upon the Changeling Soul',
	'Catch a Whiff of Madness',
	'Control the Savage Beast',
	'Crazy Like a Fox',
	'Cunning Counselor',
	'Death’s Caress',
	'Death’s Grip',
	'Denial of Aphrodite’s Favor',
	'Devious Feint',
	'Displacement Aura',
	'Distant Friend',
	'Dynamic Form',
	'Earworm',
	'Echo Psychosis',
	'Enervation of Psyche',
	'Enhance the Wild Ride',
	'Ensnaring Force',
	'Escape Clause',
	'Evil Eye',
	'Eye of Unforgiving Heaven',
	'Familiar Faces',
	'Fearful Blow',
	'Feast of Shadow',
	'Feed the Blighted Wolf',
	'Fenrir’s Boon',
	'Feral Ichor',
	'Final Strike',
	'Fist of Stone',
	'Flame’s Bane',
	'Give ‘Em Hell',
	'Guardian Lion',
	'Guardian’s Vigil',
	'Harbinger of Grace',
	'Harbinger of Vengeance',
	'Healer’s Intuition',
	'Illusory Augmentation',
	'Inertial Tampering',
	'Instantaneous Transformation',
	'Instinctive Command',
	'Kinetic Wave',
	'Ligeia’s Lament',
	'Madman’s Quill',
	'Manic Episode',
	'Martyr’s Defiance',
	'Mass Hypnosis',
	'Master of Illusion',
	'Maw of the Anaconda',
	'Memory Rift',
	'Mercurial Vitality',
	'Misleading Wounds',
	'Misplaced Affection',
	'Monologue',
	'Mortal Terror',
	'Mortician’s Secret',
	'Nightingale’s Song',
	'Ominous Premonition',
	'Perfected Instincts',
	'Poisonous Thoughts',
	'Poisonous Will',
	'Predatory Senses',
	'Press-Ganged Coven',
	'Prevailing Force',
	'Primal Grace',
	'Pulse of Undeath',
	'Quick Hands',
	'Quick Work',
	'Quickened Blood',
	'Quicksilver Contemplation',
	'Radiant Gaze',
	'Reflection of Endurance',
	'Reflection of Mercy',
	'Relentless Pursuit',
	'Rend Flesh',
	'Resplendence of the Supple Form',
	'Retain the Quick Blood',
	'Sanguinary Expulsion',
	'Savage Provocation',
	'Scalpel Tongue',
	'Second Wind',
	'Setting the Tempo',
	'Shadowcrafting',
	'Sloughing the Serpent’s Skin',
	'Smile Through the Pain',
	'Snake Den',
	'Spawning Pool',
	'Stealth Vehicle',
	'Stony Retribution',
	'Suck It Up',
	'Symbiotic Possession',
	'Sympathetic Agony',
	'Telepathic Directive',
	'Tempest Form',
	'Terror of Tentacles',
	'That Damn Cat',
	'The Iron Glare',
	'Translocation',
	'Unlock the Hidden Talent',
	'Unnatural Grace',
	'Vanishing Act',
	'Venomous Beast',
	'Vexing Hecklers',
	'Visions of the True Form',
	'Wall of Force',
	'Warrior’s Bond',
	'Weakness of Steel',
	'Will to Survive',
	'Wolf’s Blood'
]);
export type TechniqueName = z.infer<typeof techniqueName>;
