import { z } from 'zod';

export const flawName = z.enum([
	'Bond at First Taste',
	'Bond Junkie',
	'Long Bond',
	'Symbiotic Dependency',
	'Enemy',
	'Infamy',
	'Poor',
	'No Haven',
	'Obvious Predator',
	'Illiterate',
	'Known Corpse',
	'Known Blankbody',
	'Farmer',
	"Methuselah's Thirst",
	'Organovore',
	'Prey Exclusion',
	'Weak Stomach',
	'Baneful Blood',
	"Crone's Curse",
	'Distressing Fangs',
	'Bound to the Earth',
	'Eerie Presence',
	'Folkloric Bane',
	'Folkloric Block',
	'Haunted',
	'Stake Bait',
	'Stigmata',
	'Trouble Magnet',
	'Awkward Mobility',
	'Deep Sleeper',
	'Low Pain Threshold',
	'Slow Healing',
	'Archaic',
	'Dark Secret',
	'Death Sight',
	'Living on the Edge',
	'Impatient',
	'Weak Willed',
	'Baby Teeth',
	'Bestial Temper',
	'Branded by the Camarilla',
	'Clan Curse',
	'Dead Flesh',
	'Mortal Frailty',
	'Shunned by the Anarchs',
	'Vitae Dependency'
]);
export type FlawName = z.infer<typeof flawName>;
