name: Code Quality checks
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check svelte check
        run: pnpm check
        env:
          PUBLIC_CHARACTER_DB_PB_URL: ${{ secrets.PUBLIC_CHARACTER_DB_PB_URL }}
          IS_PRODUCTION: ${{ secrets.IS_PRODUCTION }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
      - name: Svelte-Check PR Annotator
        uses: prgm-dev/svelte-check-pr-annotator@v1

      - name: Check formatting with Prettier && ESLint
        run: pnpm lint
